server:
  compression:
    enabled: true
    mime-types: image/jpeg,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
spring:
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 7MB
  data:
    mongodb:
      uri: mongodb+srv://user:Val!dP@ssw0rd@cluster0.0gupx.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
